"""add cover_letter to applications

Revision ID: 2b7428ae188b
Revises: 624d5271c9f3
Create Date: 2026-07-30 17:41:30.768639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7428ae188b'
down_revision: Union[str, Sequence[str], None] = '624d5271c9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_letter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cover_letter')
    # ### end Alembic commands ###
